# Generated by Django 3.1.7 on 2022-05-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projecttasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTasks',
        ),
    ]
