# Generated by Django 3.1.7 on 2022-05-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='sites',
        ),
    ]
