# Generated by Django 3.1.7 on 2022-05-26 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Task Assigned', 'Task Assigned'), ('Accepted', 'Accepted'), ('Start Tracking', 'Start Tracking'), ('End Tracking', 'End Tracking'), ('Closed', 'Closed')], default='Task Assigned', max_length=50)),
                ('fault_description', models.TextField(blank=True, default='', null=True)),
                ('admin_remark', models.TextField(blank=True, default='', null=True)),
                ('resolved_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Resolved Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('fault_type', models.CharField(blank=True, choices=[('Active Issue', 'Active Issue'), ('Passive Issue', 'Passive Issue')], default='Passive Issue', max_length=50)),
                ('accpeted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FaultManagement_accpeted_by', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FaultManagement_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultManagement_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultManagement_modified_by', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultManagement_site', to='sites.sites', verbose_name='Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultManagement_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Task Management',
            },
        ),
        migrations.CreateModel(
            name='SiteTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default='', max_length=20)),
                ('longitude', models.CharField(default='', max_length=20)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('distance', models.FloatField(default=0.0)),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('total_time', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('status_comment', models.TextField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteTracking_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteTracking_modified_by', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteTracking_user', to='resource_tracking.faultmanagement')),
            ],
            options={
                'verbose_name_plural': 'Site Tracking',
            },
        ),
        migrations.CreateModel(
            name='SiteAssignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteAssignement_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteAssignement_modified_by', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteAssignement_site', to='sites.sites', verbose_name='Site')),
                ('user', models.ManyToManyField(related_name='SiteAssignement_user', to=settings.AUTH_USER_MODEL, verbose_name='siteassign_user')),
            ],
            options={
                'verbose_name_plural': 'Site Assignment',
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_response', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PushNotificationLog_created_by', to=settings.AUTH_USER_MODEL)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PushNotificationLog_fault', to='resource_tracking.faultmanagement')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PushNotificationLog_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PushNotificationLog_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Push Notification Log',
            },
        ),
        migrations.CreateModel(
            name='FaultImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(default='', null=True, upload_to='fault_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultSiteImages_created_by', to=settings.AUTH_USER_MODEL)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_tracking.faultmanagement')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultSiteImages_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaultComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultComments_created_by', to=settings.AUTH_USER_MODEL)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_tracking.faultmanagement')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultComments_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fault Comments',
            },
        ),
        migrations.CreateModel(
            name='FaultAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_data', models.FileField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultAssignment_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FaultAssignment_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fault Assignment',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='In Time')),
                ('out_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Out Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attendance_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Attendance',
            },
        ),
        migrations.CreateModel(
            name='TrackingSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking Summary',
                'verbose_name_plural': 'Tracking Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resource_tracking.sitetracking',),
        ),
    ]
