# Generated by Django 3.1.7 on 2022-07-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=255)),
                ('serial_number', models.CharField(default='', max_length=255)),
                ('spoc_name', models.CharField(default='', max_length=255)),
                ('spoc_contact', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('site_details', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('latitude', models.CharField(default='', max_length=20)),
                ('longitude', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('primary_link', models.CharField(default='', max_length=255)),
                ('primary_link_testing', models.CharField(default='', max_length=255)),
                ('secondary_link', models.CharField(default='', max_length=255)),
                ('secondary_link_testing', models.CharField(default='', max_length=255)),
                ('site_status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30)),
                ('site_type', models.CharField(choices=[('HUB', 'HUB'), ('SPOKE', 'SPOKE')], default='PENDING', max_length=30)),
                ('verification_status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('WAITING-FOR-APPROVAL', 'WAITING-FOR-APPROVAL'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accpeted_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_accpeted_by_id', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_project_id', to='projects.projects')),
                ('site_engineer', models.ManyToManyField(blank=True, related_name='Site_site_engineer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Site Master',
            },
        ),
        migrations.CreateModel(
            name='SiteTaskMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30, null=True)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_created_by', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_projects', to='projects.projects')),
                ('sites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_sites', to='sites.sites')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_tasks', to='tasks.tasks')),
            ],
            options={
                'verbose_name_plural': 'Site Tasks Mapper',
            },
        ),
    ]
