# Generated by Django 3.1.7 on 2022-05-26 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Master',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=255)),
                ('serial_number', models.CharField(default='', max_length=255)),
                ('spoc_name', models.CharField(default='', max_length=255)),
                ('spoc_contact', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('site_details', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('latitude', models.CharField(default='', max_length=20)),
                ('longitude', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('site_status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30)),
                ('site_type', models.CharField(choices=[('HUB', 'HUB'), ('SPOKE', 'SPOKE')], default='PENDING', max_length=30)),
                ('verification_status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('WAITING-FOR-APPROVAL', 'WAITING-FOR-APPROVAL'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_project_id', to='projects.projects')),
                ('site_engineer', models.ManyToManyField(blank=True, related_name='Site_site_engineer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Site Master',
            },
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('IN-ACTIVE', 'IN-ACTIVE')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projecttasks_created_by', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttasks_project_id', to='projects.projects')),
                ('tasks', models.ManyToManyField(blank=True, related_name='projecttasks_tasks', to='sites.Tasks')),
            ],
            options={
                'verbose_name_plural': 'Project Tasks',
            },
        ),
    ]
