# Generated by Django 3.1.7 on 2022-05-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20220526_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTasks',
        ),
    ]
