# Generated by Django 3.1.7 on 2022-05-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('sites', '0003_delete_projecttasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='Site_tasks', to='tasks.Tasks'),
        ),
    ]
