# Generated by Django 3.1.7 on 2022-05-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_sites_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='tasks',
        ),
    ]
