# Generated by Django 3.1.7 on 2022-05-26 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasks_sites'),
        ('projects', '0003_delete_projecttasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0005_remove_sites_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTaskMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30)),
                ('file', models.FileField(max_length=254, upload_to=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projecttasks_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_project', to='projects.projects')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_site', to='projects.projects')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_tasks', to='tasks.tasks')),
            ],
            options={
                'verbose_name_plural': 'Site Tasks Mapper',
            },
        ),
    ]
