# Generated by Django 3.1.7 on 2022-05-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_projecttasks'),
        ('sites', '0006_sitetaskmapper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetaskmapper',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sitetaskmapper',
            name='site',
        ),
        migrations.AddField(
            model_name='sitetaskmapper',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_projects', to='projects.projects'),
        ),
        migrations.AddField(
            model_name='sitetaskmapper',
            name='sites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_sites', to='sites.sites'),
        ),
    ]
