# Generated by Django 3.1.7 on 2022-05-26 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0007_auto_20220526_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetaskmapper',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sitetaskmapper_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
