# Generated by Django 3.1.7 on 2022-05-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20220526_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetaskmapper',
            name='file',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='sitetaskmapper',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=30, null=True),
        ),
    ]
