# Generated by Django 3.1.7 on 2022-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_auto_20220526_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='primary_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sites',
            name='primary_link_testing',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sites',
            name='secondary_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sites',
            name='secondary_link_testing',
            field=models.CharField(default='', max_length=255),
        ),
    ]
