# Generated by Django 3.1.7 on 2022-05-27 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0010_auto_20220526_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='accpeted_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites_accpeted_by_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
